### ISSUE TITLE
[BUG]: Invalid variable 

### ISSUE THREAD

**Issue by TESTAPIS21** [kid1194/erpnext_expenses#2]
![image](https://github.com/kid1194/erpnext_expenses/assets/87822032/24943e2d-5208-4211-bf28-450470bbe286)
![image](https://github.com/kid1194/erpnext_expenses/assets/87822032/e85dff8a-eaf7-469e-adbc-bd253ca3631a)

**Comment by kid1194** [comment]
@TESTAPIS21 Thank you so much for reporting this bug..

Please update the plugin and let me know if there are any other issues..

Best regards..
