### ISSUE TITLE
[REQ]: 

### ISSUE THREAD

**Issue by washaqq** [kid1194/erpnext_expenses#4]
Hi,

since expenses is a part of accounting it should be under Accounting Module, 
![resim](https://github.com/kid1194/erpnext_expenses/assets/16055736/fd647a84-21b5-4121-8651-e1550fb0e20a)

Yes, i can add it by editing workspace but, it would be nice if it built that way,
![resim](https://github.com/kid1194/erpnext_expenses/assets/16055736/1c1f3923-98e1-4159-b226-8396f60399ba)

**Comment by kid1194** [comment]
@washaqq Thanks bro for recommending that..

In the last update I have removed the "Expenses" workspace and added the a link to each Expenses doctype into the "Accounting" workspace..

Best regards..
