### ISSUE TITLE
[BUG]: INSTALLING EXPENSES

### ISSUE THREAD

**Issue by capabl3** [kid1194/erpnext_expenses#6]
**Describe the bug**
ImportError: Module import failed for Expenses Entry, the DocType you're trying to open might be deleted.
Error: cannot import name '__ACCOUNT__' from 'expenses.libs' (apps/expenses/expenses/libs/__init__.py)

**To Reproduce**
1. cd ~/frappe-bench
2. bench get-app https://github.com/kid1194/erpnext_expenses
3. bench --site [sitename] install-app expenses

**Expected behavior**

Installing expenses...
Updating DocTypes for expenses      : [==                                      ] 6%An error occurred while installing expenses: Module import failed for Expenses Entry, the DocType you're trying to open might be deleted.<br> Error: cannot import name '__ACCOUNT__' from 'expenses.libs' (/home/iak/frappe-bench/apps/expenses/expenses/libs/__init__.py)
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 462, in install_app
    _install_app(app, verbose=context.verbose, force=force)
      context = {'sites': ['bollexmedia.com'], 'force': False, 'verbose': False, 'profile': False}
      apps = ('expenses',)
      force = True
      _install_app = <function install_app at 0x7f95cc7a4ae0>
      filelock = <function filelock at 0x7f95cc79eca0>
      exit_code = 0

**Additional context**
Frappe and ERPNEXT Version 15

**Comment by kid1194** [comment]
@iakah Hey bro, thank you for reporting this problem..

I have updated the plugin and I hope that it works well for you, but if doesn't please inform me..

I really appreciate your patience and giving the plugin another try..

Best regards..

**Comment by capabl3** [comment]
Hello @kid1194  thank you for the swift response. I  have tried it again and although now the migration is stopping at 12% instead of the previous 6%, it's still bringing the same error.  Kindly see below.

Installing expenses...
Updating DocTypes for expenses      : [=====                                   ] 12%An error occurred while installing expenses: Module import failed for Expense Type Account, the DocType you're trying to open might be deleted.<br> Error: cannot import name '__ACCOUNT__' from 'expenses.libs' (/home/iak/frappe-bench/apps/expenses/expenses/libs/__init__.py)
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 462, in install_app

**Comment by kid1194** [comment]
@iakah Thank you bro for giving it another try and for reporting the error..

I just want to as if you have ERPNext installed or not?

Because the "Account" Doctype that is mentioned in the error belongs to ERPNext..

Best regards..

**Comment by capabl3** [comment]
Hi @kid1194 , yes I have erpnext installed.

**Comment by kid1194** [comment]
@iakah Thank you bro for your response..

Can you please give it another try. I hope it gets installed this time..

And I hope that you like my small gesture of appreciation by adding your name in the list of contributors..

Best regards..

**Comment by capabl3** [comment]
Hi @kid1194 thank you for the gesture and for your help debugging the application.

It has now been installed but however, there is one last validation error. kindly see below.
...................................................................................
App erpnext already installed

Installing expenses...
Updating DocTypes for expenses      : [========================================] 100%
An error occurred while installing expenses: Cannot change state of Cancelled Document. Transition row 14
Traceback with variables (most recent call last):


 raise_exception = <class 'frappe.exceptions.ValidationError'>
frappe.exceptions.ValidationError: Cannot change state of Cancelled Document. Transition row 14 raise_exception = <class 'frappe.exceptions.ValidationError'>
frappe.exceptions.ValidationError: Cannot change state of Cancelled Document. Transition row 14

**Comment by kid1194** [comment]
@iakah Thank you for reporting this bro..

I have fixed workflow transition and now it should work..

So, kindly please give it another chance and try installing it again..

Best regards..

**Comment by capabl3** [comment]
It now works, thank you @kid1194, your response is swift and Kudos for the great work.

**Comment by kid1194** [comment]
@iakah I'm glad to hear that it worked..

If you find any bug please let me know and I will be happy to fix it..

Best regards..

**Comment by capabl3** [comment]
Hi @kid1194 , I found the following bugs on accessing it under accounting module.....

1. [Expense Attachment ]
,[Expense Item Account ]
,[Expense Type Account ]
,[Expenses Entry Details ]
,[Expenses Request Details ]
 and Expenses Update Receiver pages are missing.
2. Under new expense type I get the following error:  ### App Versions
```
{
	"erpnext": "15.10.1",
	"expenses": "1.0.0",
	"frappe": "15.9.0"
}
```
### Route
```
Form/Expense Type/new-expense-type-upjxfthbps
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1682, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/expenses/expenses/libs/type.py", line 28, in type_form_setup
    "has_accounts": get_types_with_accounts("Expense Type")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: get_types_with_accounts() takes 0 positional arguments but 1 was given

```
### Request Data
```
{
	"type": "POST",
	"args": {},
	"freeze": false,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/expenses.libs.type_form_setup",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "TypeError: get_types_with_accounts() takes 0 positional arguments but 1 was given",
	"exc_type": "TypeError",
	"_exc_source": "expenses (app)"
}
```

**Comment by kid1194** [comment]
@iakah Hey bro, a million thanks for reporting this..

It seems that the app wasn't fully installed.

I have fixed the bug so please give it another try and check if these doctypes exist after install or not..

Please let me know if you face any problem..

Also, if you are using discord, this is the Exoenses app thread..
[ERPNext Expenses App](https://discord.com/invite/XywzmHGmaY)

Best regards..

**Comment by capabl3** [comment]
Hi @kid1194 , the doctypes have still not yet showed.

**Comment by kid1194** [comment]
@iakah Sorry bro about that..

I suspected the cleanup code that is run before install and after uninstall..

I have made small changes in that code and I hope that it fixes the problem because I haven't found anything that might cause such problem..

Please give it another try and try to uninstall it first then install again..

I will be waiting patiently for your response..

Thanks a lot again and again..

Best regards..

**Comment by kid1194** [comment]
@iakah Hey bro..

I just wanted to know if you managed to install the expenses app or not?

Best regards..

**Comment by capabl3** [comment]
Hello Bruv, I managed to install it..however, there are some issues..., the following pages are missing when I click the following.. [Expense Attachment ]
,[Expense Item Account ]
,[Expense Type Account ]
,[Expenses Entry Details ]
,[Expenses Request Details ]
and Expenses Update Receiver pages are missing.

Moreover, Under new expense type I get an error: ###

 {
	"exception": "TypeError: get_types_with_accounts() takes 0 positional arguments but 1 was given",
	"exc_type": "TypeError",
	"_exc_source": "expenses (app)"
}

<img width="751" alt="Screenshot 2024-01-25 021101" src="https://github.com/kid1194/erpnext_expenses/assets/37710249/b96766e1-6381-46d3-8268-fd60b5b3202a">
<img width="809" alt="Screenshot 2024-01-25 021026" src="https://github.com/kid1194/erpnext_expenses/assets/37710249/7165bad3-d533-41e1-a9f6-c15ffe27b65b">
<img width="824" alt="Screenshot 2024-01-25 020947" src="https://github.com/kid1194/erpnext_expenses/assets/37710249/51e05160-096f-48c6-a872-72ed614c6ad8">


Also the new expense entry page seems to be blank

<img width="941" alt="Screenshot 2024-01-25 021437" src="https://github.com/kid1194/erpnext_expenses/assets/37710249/0ebea081-6703-4937-b261-255530983a00">


thank you for reaching out @kid1194. Lets work on these.

**Comment by kid1194** [comment]
@iakah Hey bro..

Thanks for your reply..

I think that the problem is because bench is installing the app from cache which is not the updated version from github..

So can you please fully uninstall the app using the following commands and then install it again..

#### Uninstall
1. Go to bench directory

```
cd ~/frappe-bench
```

2. Uninstall plugin from your site

```
bench --site [sitename] uninstall-app expenses
```

3. Remove plugin from bench

```
bench remove-app expenses
```

4. (Optional) Restart bench

```
bench restart
```

But if you don't have bench access then let me know so I can find another way..

Best regards..

**Comment by capabl3** [comment]
Hello @kid1194 , I have followed the above commands and also deleted the archived apps still to no luck....

What might be the problem?

Let me know what you need so that we can solve this.

**Comment by kid1194** [comment]
@iakah Thank you for your great response..

I have made some modifications that I hope will fix this problem..

So please kindly give it another try..

Best regards..

**Comment by capabl3** [comment]
@kid1194  thanks, the problem hasn't been fixed yet

**Comment by kid1194** [comment]
@iakah Hey bro..

Can you please give it another try. I have checked the whole code and I made some changes, so hopefully it works this time..

If it doesn't, then sadly I can say that I have no idea about what is causing this problem..

Best regards..

**Comment by kid1194** [comment]
@iakah Hey buddy..

I have made a lot if changes to the module and it is working without any problem, unless I have missed something..

So please give it another try and let me know if you face any problem..

Best regards..
