### ISSUE TITLE
[REQ]: 

### ISSUE THREAD

**Issue by forteqt** [kid1194/erpnext_expenses#8]
Can you brief what expenses.bunble.js is doing or similar addons that are non native? Unlike the native application, it feels like the expenses app is using different addons, so its hard to catch upon how issues  and cant be related to native behaviors from other part of the app. If you can give a brief about the concept, that would be helpful to work around with.

**Comment by kid1194** [comment]
@forteqt  Hey bro..

Sorry for the late reply, I have been busy fixing this module 😁

This js file contains several utility classes & functions..

Please check out the latest update and let me know if you face any problem..

Best regards..
